### ISSUE TITLE
Speed up devcontainer build

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs.github.io#144]
Not sure why but my devcontainer/codespace for the website takes incredibly long to build.

Perhaps we can investigate and make sure that we're not over-installing dependencies.

**Comment by oleksis** [comment]
I will push the image to GitHub Container registry

**Comment by jefftriplett** [comment]
From other Jekyll + GitHub Pages + Docker setups I have used, we have struggled to get Ruby to keep a cache of everything it needs to run. It's been a year(ish) since I looked, but it used to do a fresh `gem install` when the container started. 

If @oleksis's container is doing that then using the image should help skip a bunch of slow steps.

**Comment by oleksis** [comment]
Thanks for the advice @jefftriplett

**Comment by oleksis** [comment]
## External links

- [Speed Up Your Workflow with Prebuilds](https://containers.dev/guide/prebuild)
- [Prebuilding your codespaces](https://docs.github.com/en/codespaces/prebuilding-your-codespaces)

**Comment by oleksis** [comment]
[BPDevs Codespaces](https://gist.github.com/oleksis/3dae07876c5de06a13729960270ddf6f#bpdevs-codespaces)
[DevContainers and Codespaces](https://gist.github.com/oleksis/05f47ebc736a5c311c2bbef0bd5ca1ad#dockerfile)
[BPDevs Visual Studio Code Profile](https://gist.github.com/oleksis/ac4b7b4e3abed1a40de008721fe0233b)

**Comment by kjaymiller** [comment]
Great work on speeding up the build. I wonder if there is something we can do on the local end. It's still relatively slow. 

I do wonder what the balance should be as our codespaces container is now almost 5GB!

**Comment by oleksis** [comment]
Thank @kjaymiller, We can make the image smaller if we don't need Docker in Docker or Act

https://github.com/BlackPythonDevs/blackpythondevs.github.io/blob/64a13a03c949710d1c9f23fa54585a23a4cae485/.devcontainer/devcontainer.json#L19-L20 

And instead of compiling Python add [Python as a DevContainers feature](https://github.com/devcontainers/features/tree/main/src/python)

**Comment by kjaymiller** [comment]
I think we don't need docker-in-docker as we're not packaging anything in our application. (If I remember act was why you needed docker-indocker)

**Comment by oleksis** [comment]
Correct then I will update the `devcontainer.json`
