### ISSUE TITLE
Conference page translations missing for Spanish and Swahili

### ISSUE THREAD

**Issue by cmm25** [BlackPythonDevs/blackpythondevs.github.io#433]
# Conference page translations missing for Spanish and Swahili

![image](https://github.com/user-attachments/assets/c869f0c2-d493-4b8f-ad43-19b200abd382)

## Description

Playwright tests are failing due to missing translations for the conference page in Spanish and Swahili. This is causing 404 timeout errors during the tests.

## Specific Issues

1. Spanish translation for the conference page is missing
2. Swahili translation for the conference page is missing

## Impact

- Playwright tests are failing
- Users trying to access the conference page in Spanish or Swahili will encounter a 404 error

**Comment by TimOsahenru** [comment]
We no longer have a dedicated conference page for all translations, as they have been merged into the events page: https://blackpythondevs.com/events/. The reason for the failing tests is that the tests were still attempting to access the `/conference` endpoint, which has since been removed and failing tests fixed in this PR https://github.com/BlackPythonDevs/blackpythondevs.github.io/pull/435
